### ISSUE TITLE
Data files are missing

### ISSUE THREAD

**Issue by scisterna** [PacktPublishing/Data-Analytics-for-Marketing#1]
Hi!
There is a lot of data files that are missing in the book. I haven't finished it yet but so far these are missing:

- C03 data/campaign_data.csv
- C05. ../data/superstore.csv
- C06 ./data/anomaly_data.csv
- C07 '../data/retail_rfm.csv'
- C07 ("retail_segmentation.csv")

**Comment by rahul-packt** [comment]
Hey @gdberrio ! Could you please help us on this?

**Comment by gdberrio** [comment]
Hi @scisterna, apologies for the delay. I've pushed a new commit with the data files inside the correct chapter folders.
